apiVersion: batch/v1
kind: CronJob
metadata:
  name: tiktok-brigade-fetch-data
spec:
  schedule: "0 5 * * *" # 5 AM every day
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: tiktok-brigade-fetch-data
            image: tiktok-brigade
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: tiktok_brigade.settings.k8s
              - name: PYTHONUNBUFFERED
                value: "true"
            envFrom:
              - secretRef:
                  name: tiktok-brigade-credentials
            command:
              - ./run.sh
          restartPolicy: Never
