apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tiktok-brigade
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
  - cronjob-export.yaml

images:
  - name: tiktok-brigade
    newName: rg.fr-par.scw.cloud/djnd/tiktok-brigade
    newTag: '53f990c1c95a32e85198ba23f2ee61a1dfe9b7ac'
