apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tiktok-brigade
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
  - cronjob-export.yaml

images:
  - name: tiktok-brigade
    newName: rg.fr-par.scw.cloud/djnd/tiktok-brigade
    newTag: '5aced9ba0f8ae01dc7cc8b9d684e532482008d29'
