# Generated by Django 6.0 on 2025-12-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TikTokProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("profile_url", models.URLField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="tiktok.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Profile",
                "verbose_name_plural": "TikTok Profiles",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="TikTokVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("video_url", models.URLField()),
                ("play_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="tiktok.tiktokprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Video",
                "verbose_name_plural": "TikTok Videos",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="TikTokVideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.CharField(max_length=255, unique=True)),
                ("author_username", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tiktok.tiktokvideo",
                    ),
                ),
            ],
        ),
    ]
