# Generated by Django 6.0 on 2025-12-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("author_username", models.CharField(max_length=255)),
                ("author_nickname", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("avatar_url", models.URLField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tiktok.tiktokcomment",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tiktok.tiktokvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Comment",
                "verbose_name_plural": "TikTok Comments",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.DeleteModel(
            name="TikTokVideoComment",
        ),
    ]
