# Generated by Django 6.0 on 2025-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_tiktokcomment_delete_tiktokvideocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcomment',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
